.TH "vector_t" 3 "Version 0.1.0" "shana" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vector\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.RI "raw table "
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "number of elements "
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.RI "allocated capacity "
.ti -1c
.RI "size_t \fBelement_size\fP"
.br
.RI "size of an element "
.in -1c
.SH "Detailed Description"
.PP 
The \fBvector_t\fP structure is designed to represent a generic vector in C\&. This means that it can store elements of any type (integers, floats, other structures, etc\&.) without being specifically tied to a single type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for shana from the source code\&.
